import type { AnalysisResult, Vendor } from "@/types/network";

export type CollectionProfileId = "internet-down" | "duplicate-ip" | "mac-flapping" | "link-flap" | "dhcp-failure" | "network-slow" | "routing" | "sdwan-down";

export interface CollectionCommand {
  command: string;
  reason: { en: string; th: string };
}

export interface CollectionProfile {
  id: CollectionProfileId;
  vendors: Vendor[];
  title: { en: string; th: string };
  description: { en: string; th: string };
  commands: CollectionCommand[];
}

const c = (command: string, en: string, th: string): CollectionCommand => ({ command, reason: { en, th } });

export const COLLECTION_PROFILES: CollectionProfile[] = [
  { id: "internet-down", vendors: ["cisco"], title: { en: "Internet access failure", th: "เครื่องใช้อินเทอร์เน็ตไม่ได้" }, description: { en: "Trace endpoint, VLAN, uplink, and routing evidence.", th: "เก็บหลักฐานตั้งแต่เครื่องปลายทาง VLAN uplink และ routing" }, commands: [c("show ip arp", "Maps IP to ARP evidence.", "ตรวจ IP และ ARP"), c("show mac address-table", "Maps MAC to switch port.", "หา MAC และพอร์ต"), c("show interfaces status", "Checks port link state.", "ตรวจสถานะพอร์ต"), c("show interfaces description", "Adds port purpose.", "ดูคำอธิบายพอร์ต"), c("show interfaces counters errors", "Checks physical errors.", "ตรวจ error บนพอร์ต"), c("show vlan brief", "Checks VLAN membership.", "ตรวจ VLAN"), c("show interfaces switchport", "Checks access/trunk settings.", "ตรวจ switchport"), c("show ip route", "Checks route reachability.", "ตรวจ routing"), c("show logging", "Finds relevant events.", "ตรวจ log") ] },
  { id: "duplicate-ip", vendors: ["cisco"], title: { en: "Duplicate IP", th: "IP ซ้ำ" }, description: { en: "Correlate ARP, DHCP, binding, and security evidence.", th: "เทียบ ARP DHCP binding และหลักฐาน security" }, commands: [c("show ip arp", "Identifies current IP/MAC mappings.", "ดู IP/MAC ปัจจุบัน"), c("show ip dhcp binding", "Checks active leases.", "ดู DHCP lease"), c("show ip dhcp conflict", "Checks DHCP conflict history.", "ดู DHCP conflict"), c("show ip dhcp snooping binding", "Checks snooping bindings.", "ดู snooping binding"), c("show ip source binding", "Checks source bindings.", "ดู source binding"), c("show mac address-table", "Locates each MAC.", "หา MAC บนพอร์ต"), c("show logging", "Finds duplicate/security events.", "ดู log") ] },
  { id: "mac-flapping", vendors: ["cisco"], title: { en: "MAC flapping", th: "MAC Flapping" }, description: { en: "Verify Layer 2 movement, loops, and port-channel state.", th: "ตรวจการย้าย MAC, loop และ port-channel" }, commands: [c("show logging", "Finds MAC move events.", "ดูเหตุการณ์ MAC move"), c("show mac address-table", "Shows current learned port.", "ดูพอร์ต MAC ปัจจุบัน"), c("show spanning-tree", "Checks STP roles.", "ตรวจ STP"), c("show spanning-tree detail", "Checks STP changes.", "ตรวจ STP detail"), c("show etherchannel summary", "Checks bundle consistency.", "ตรวจ EtherChannel"), c("show interfaces status", "Checks member ports.", "ตรวจพอร์ต"), c("show interfaces counters errors", "Checks physical symptoms.", "ตรวจ error") ] },
  { id: "link-flap", vendors: ["cisco"], title: { en: "Port down or link flap", th: "Port Down หรือ Link Flap" }, description: { en: "Correlate interface state, counters, STP, and logs.", th: "เทียบสถานะพอร์ต counter STP และ log" }, commands: [c("show interfaces status", "Checks current status.", "ดูสถานะปัจจุบัน"), c("show interfaces description", "Identifies service owner.", "ระบุบริการบนพอร์ต"), c("show interfaces", "Checks line protocol and errors.", "ดู line protocol"), c("show interfaces counters errors", "Checks error counters.", "ดู error counter"), c("show logging", "Finds down/up timeline.", "ดูเหตุการณ์ down/up"), c("show errdisable recovery", "Checks err-disable recovery.", "ดู err-disable"), c("show spanning-tree inconsistentports", "Checks STP inconsistent ports.", "ดู STP inconsistent") ] },
  { id: "dhcp-failure", vendors: ["cisco"], title: { en: "DHCP failure", th: "DHCP ใช้งานไม่ได้" }, description: { en: "Verify pool capacity, lease, conflicts, snooping, DAI, and source binding.", th: "ตรวจ pool lease conflict snooping DAI และ source binding" }, commands: [c("show ip dhcp pool", "Checks DHCP pool capacity.", "ดู DHCP pool"), c("show ip dhcp binding", "Checks leases.", "ดู DHCP binding"), c("show ip dhcp conflict", "Checks conflicts.", "ดู DHCP conflict"), c("show ip dhcp snooping", "Checks snooping policy.", "ดู DHCP snooping"), c("show ip dhcp snooping binding", "Checks bindings.", "ดู snooping binding"), c("show ip arp inspection", "Checks DAI state.", "ดู DAI"), c("show ip source binding", "Checks IP source guard bindings.", "ดู source binding"), c("show logging", "Finds denials and failures.", "ดู log") ] },
  { id: "network-slow", vendors: ["cisco"], title: { en: "Network slow", th: "Network ช้า" }, description: { en: "Collect interface, resource, and QoS evidence.", th: "เก็บหลักฐาน interface, resource และ QoS" }, commands: [c("show interfaces", "Checks errors and utilization.", "ดู interface"), c("show interfaces counters errors", "Checks counter errors.", "ดู error"), c("show processes cpu", "Checks CPU pressure.", "ดู CPU"), c("show memory statistics", "Checks memory pressure.", "ดู memory"), c("show environment", "Checks hardware health.", "ดู environment"), c("show logging", "Finds system events.", "ดู log"), c("show policy-map interface", "Checks QoS statistics.", "ดู QoS") ] },
  { id: "routing", vendors: ["cisco"], title: { en: "Routing abnormality", th: "Routing ผิดปกติ" }, description: { en: "Collect route, VRF, gateway, and redundancy evidence.", th: "เก็บ route VRF gateway และ redundancy" }, commands: [c("show ip route", "Checks routes and next hops.", "ดู routing table"), c("show vrf", "Checks VRF membership.", "ดู VRF"), c("show ip interface brief", "Checks gateway interfaces.", "ดู interface IP"), c("show standby brief", "Checks HSRP.", "ดู HSRP"), c("show vrrp brief", "Checks VRRP.", "ดู VRRP"), c("show logging", "Finds routing events.", "ดู log") ] },
  { id: "sdwan-down", vendors: ["cisco"], title: { en: "SD-WAN down", th: "SD-WAN Down" }, description: { en: "Collect Cisco SD-WAN control, BFD, OMP, path, and endpoint evidence.", th: "เก็บข้อมูล Cisco SD-WAN control BFD OMP path และ endpoint" }, commands: [c("show sdwan control connections", "Checks controller sessions.", "ดู control connection"), c("show sdwan bfd sessions", "Checks BFD health.", "ดู BFD"), c("show sdwan omp peers", "Checks OMP peers.", "ดู OMP peer"), c("show sdwan omp routes", "Checks OMP routes.", "ดู OMP route"), c("show sdwan interface", "Checks transport interfaces.", "ดู SD-WAN interface"), c("show sdwan app-route stats", "Checks application paths.", "ดู app-route"), c("show endpoint-tracker", "Checks endpoint tracking.", "ดู endpoint tracker"), c("show logging", "Finds control-plane events.", "ดู log") ] }
];

export function missingCollectionCommands(result: AnalysisResult, profile: CollectionProfile): CollectionCommand[] {
  const collected = new Set(result.commandBlocks.map(block => block.rawCommand.toLowerCase()));
  return profile.commands.filter(item => !collected.has(item.command.toLowerCase()));
}
